// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoZY_aNCpNqL7LzYP7NWA-K0FQVSTvxW8',
    appId: '1:795180597048:web:b6dda90cda4aca9097cbcd',
    messagingSenderId: '795180597048',
    projectId: 'ai-collection-0',
    authDomain: 'ai-collection-0.firebaseapp.com',
    storageBucket: 'ai-collection-0.appspot.com',
    measurementId: 'G-GN6Y17XMYD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFJ_UgKN2pAeuh2CNeWf8vAI5Lqb0vglQ',
    appId: '1:795180597048:android:0e6f7839a03dacec97cbcd',
    messagingSenderId: '795180597048',
    projectId: 'ai-collection-0',
    storageBucket: 'ai-collection-0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3szmXzBABL8XFnGGcj-qe6MmKibpWyks',
    appId: '1:795180597048:ios:3a35383cee3e6bdf97cbcd',
    messagingSenderId: '795180597048',
    projectId: 'ai-collection-0',
    storageBucket: 'ai-collection-0.appspot.com',
    iosClientId: '795180597048-s3te9ik994k0s0us55372trk0crd4av8.apps.googleusercontent.com',
    iosBundleId: 'com.king.ai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3szmXzBABL8XFnGGcj-qe6MmKibpWyks',
    appId: '1:795180597048:ios:195c66f32982355b97cbcd',
    messagingSenderId: '795180597048',
    projectId: 'ai-collection-0',
    storageBucket: 'ai-collection-0.appspot.com',
    iosClientId: '795180597048-4caf87hk4rn5us7efnu4t6el1o1bikul.apps.googleusercontent.com',
    iosBundleId: 'com.king.ai.RunnerTests',
  );
}
